import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/About.module.scss';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Map from '../components/Map';
import SmallPageHeader from '../components/SmallPageHeader';

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobajoy | om oss</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className={styles.main}>
        <SmallPageHeader title="Om oss" />
        <div className={styles.section} data-aos="fade-up">
          <div className={styles.textWrapper}>
            <h2 className={styles.title}>Vår reise</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda
              nesciunt cumque dolorem labore reprehenderit, amet quas similique
              quaerat fugit odio vel nihil eligendi iure animi quos, alias at
              repellat vitae?
            </p>
          </div>
        </div>
        <Map />
      </main>
      <Footer />
    </div>
  );
};

export default About;
