import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';
import logo from '../public/images/logo.png';
import Header from '../components/header';
import Footer from '../components/footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobajoy | hjem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroWrapper}>
            <div className={styles.titleWrapper}>
              <Image
                src="/images/bear_logo.svg"
                alt="BobaJoy polarbear logo"
                width={100}
                height={256}
              />
              <Image
                src={logo}
                alt="BobaJoy text logo"
                width={300}
                height={28}
              />
              <h2>Bubble tea & more</h2>
            </div>
            <div className={styles.buttonWrapper}>
              <Link href="/menu">
                <a className="btn">Bestill nå</a>
              </Link>
            </div>
          </div>
          <svg
            viewBox="0 0 1440 161"
            className={styles.heroWave}
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
          >
            <path
              d="M1359.6 17.4496L1440 26.2915V161H0V43.9754L80.3999 55.7646C159.6 67.5538 320.4 91.1323 480 79.3431C639.6 67.5539 800.4 20.3969 960 5.66039C1119.6 -9.07616 1280.4 8.6077 1359.6 17.4496Z"
              fill="#F2F3DA"
            />
            <path
              d="M1440 44.7354L1359.6 35.8935C1280.4 27.0515 1119.6 9.36769 960 24.1042C800.4 38.8408 639.6 85.9977 480 97.7869C320.4 109.576 159.6 85.9977 80.3999 74.2085L0 62.4192"
              stroke="#BDCA4D"
              strokeWidth="8"
              strokeLinecap="square"
            />
            <path
              d="M1440 66.2915L1359.6 57.4496C1280.4 48.6077 1119.6 30.9238 960 45.6604C800.4 60.3969 639.6 107.554 480 119.343C320.4 131.132 159.6 107.554 80.3999 95.7646L0 83.9754"
              stroke="#BDCA4D"
              strokeWidth="8"
              strokeLinecap="square"
            />
          </svg>
        </div>
        <div className={`${styles.section} ${styles.gridWrapper}`}>
          <div className={styles.grid}>
            <div className={styles.welcomeText}>
              <div>
                <h2>Vi ønsker deg velkommen til Bobajoy</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id
                  ipsum scelerisque volutpat felis, felis consequat viverra.
                  Ullamcorper a amet, euismod venenatis amet...
                </p>
              </div>
              <div className={styles.buttonWrapper}>
                <Link href="/menu">
                  <a className="btn">Les mer om oss</a>
                </Link>
              </div>
            </div>
            <div>
              <h2>Her finner du oss</h2>
              <p>
                Olav Tryggvason gt. 1, 7011 Trondheim Lorem ipsum dolor sit
                amet, consectetur adipiscing elit.{' '}
              </p>
            </div>
            <div>
              <h2>Del dine bobler sammen med oss!</h2>
              <p>#bobajoyno</p>
              <p>#bobajoy</p>
            </div>
          </div>
        </div>
        <div className={styles.section}>
          <h1 className={styles.title}>Utvalgte teer</h1>
        </div>
        <div className={styles.section}>
          <h1 className={styles.title}>Følg oss på instagram!</h1>
        </div>
        <div className={styles.section}>map</div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
