import { FC } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import Header from '../components/Header';
import styles from '../styles/Order.module.scss';
import { items } from '../utilities/items';
import SmallPageHeader from '../components/SmallPageHeader';
import Map from '../components/Map';

const OrderItem: FC<{ value: Item }> = ({ value }) => {
  return (
    <div className={styles.orderItem}>
      <div className={styles.orderItemInfo}>
        <h3>{value.name}</h3>
        <p>{value.description}</p>
        <p className={styles.orderItemPrice}>{value.price}</p>
      </div>
      <div className={styles.orderItemImage}>
        <Image
          src={value.image}
          alt="A placeholder for images"
          width={320}
          height={320}
          layout="responsive"
        />
      </div>
    </div>
  );
};

const Order: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobajoy | bestill</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className={styles.main}>
        <SmallPageHeader title="Bestill" />
        <div className={styles.section}>
          <div className={styles.orderWrapper}>
            <h1 className={styles.title}>Bestillingsskjema</h1>
            <div className={styles.orderDisplay}>
              <div className={styles.orderNav}>
                {items.map((item) => (
                  <button key={item.key}>{item.key}</button>
                ))}
              </div>
              <div className={styles.orderItems}>
                {items.map((item, i) => {
                  return (
                    <div className={styles.orderItemsWrapper} key={i}>
                      <div className={styles.orderItemsInfo}>
                        <h2>{item.key}</h2>
                        <p>{item.description}</p>
                      </div>
                      <div className={styles.orderItemsList}>
                        {item.values.map((value: Item, itemId) => (
                          <OrderItem key={i + '_' + itemId} value={value} />
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className={styles.orderInfo}>
                <h2>Min bestilling</h2>
                <p>2 varer</p>
                <div className={styles.orderInfoItems}>
                  <div className={styles.orderInfoItem}>
                    <p>1- Plain Milk Tea - Black (Medium size)</p>
                    <p>60kr</p>
                  </div>
                  <div className={styles.orderInfoItem}>
                    <p>1- Plain Milk Tea - Black (Large size)</p>
                    <p>60kr</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Map />
      </main>
      <Footer />
    </div>
  );
};

export default Order;
